name: .NET CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    
    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        global-json-file: 'dot-net/global.json'
    
    - name: Restore dependencies
      run: dotnet restore dot-net/ReliableDownloader.sln
    
    - name: Build
      run: dotnet build dot-net/ReliableDownloader.sln --no-restore
    
    - name: Test
      run: dotnet test dot-net/ReliableDownloader.sln --no-build --verbosity normal
