name: .NET Core CI

on:
  push:
  pull_request:
    branches:
      - main

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./dot-net

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup .NET SDK
        uses: actions/setup-dotnet@v4
        with:
          # You can specify a .NET version here if needed, e.g., '6.0.x'
          # Or, if you have a global.json file, you can point to it:
          # global-json-file: dot-net/global.json 
          dotnet-version: '8.0.x' # Using a recent LTS version as an example

      - name: Restore dependencies
        run: dotnet restore ReliableDownloader.sln

      - name: Build project
        run: dotnet build ReliableDownloader.sln --configuration Release --no-restore

      - name: Run tests
        run: dotnet test ReliableDownloader.sln --no-build --configuration Release --verbosity normal
